In [8]:
import numpy as np
import cv2

In [3]:
original = [
    [15, 15, 15, 15, 15, 15, 15],
    [15, 0, 10, 10, 8, 11, 15],
    [15, 4, 15, 9, 15, 15, 15],
    [15, 4, 12, 10, 14, 15, 15],
    [15, 4, 15, 9, 15, 15, 15],
    [15, 0, 2, 2, 0, 11, 15],
    [15, 15, 15, 15, 15, 15, 15],
]

original = np.array(original)

In [4]:
L = 15

negatives = 15 - original

In [5]:
negatives

array([[ 0,  0,  0,  0,  0,  0,  0],
       [ 0, 15,  5,  5,  7,  4,  0],
       [ 0, 11,  0,  6,  0,  0,  0],
       [ 0, 11,  3,  5,  1,  0,  0],
       [ 0, 11,  0,  6,  0,  0,  0],
       [ 0, 15, 13, 13, 15,  4,  0],
       [ 0,  0,  0,  0,  0,  0,  0]])

In [6]:
def bitplane_slice(img, bit):
    return (img >> bit) & 1

In [7]:
planes = [bitplane_slice(negatives, i) for i in range(4)]

planes

[array([[0, 0, 0, 0, 0, 0, 0],
        [0, 1, 1, 1, 1, 0, 0],
        [0, 1, 0, 0, 0, 0, 0],
        [0, 1, 1, 1, 1, 0, 0],
        [0, 1, 0, 0, 0, 0, 0],
        [0, 1, 1, 1, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 0]]),
 array([[0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 1, 0, 0],
        [0, 1, 0, 1, 0, 0, 0],
        [0, 1, 1, 0, 0, 0, 0],
        [0, 1, 0, 1, 0, 0, 0],
        [0, 1, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 0]]),
 array([[0, 0, 0, 0, 0, 0, 0],
        [0, 1, 1, 1, 1, 1, 0],
        [0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0],
        [0, 1, 1, 1, 1, 1, 0],
        [0, 0, 0, 0, 0, 0, 0]]),
 array([[0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0],
        [0, 1, 1, 1, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 0]])]

In [9]:
cv2.imwrite('7-1.png', planes[0] * 255)
cv2.imwrite('7-2.png', planes[1] * 255)
cv2.imwrite('7-3.png', planes[2] * 255)
cv2.imwrite('7-4.png', planes[3] * 255)

True